### ISSUE TITLE
Shadow bug and floating plants

### ISSUE THREAD

**Issue by MarkuBu** [duane-r/fun_caves#1]
I tried fun_caves v6 with the current minetest dev, no other mods and flat mapgen or v5. I can find the same issues like in valleys mg. Shadows and floating/destroyed plants.

![screenshot_20160506_153156](https://cloud.githubusercontent.com/assets/16163058/15074560/f7f86ea6-139f-11e6-9cb1-93aef3e41fda.png)
![screenshot_20160506_153305](https://cloud.githubusercontent.com/assets/16163058/15074568/012d1d5a-13a0-11e6-815c-5e4e3a1d9642.png)

**Comment by duane-r** [comment]
I'm getting those same, square shadows in minetest game with no mods added.

**Comment by MarkuBu** [comment]
I made an experiment. I disabled dungeons, caves and decorations and flew around. I flew 3 or 4 ingame days without any shadow. Then I enabled only caves, only decoration and both without any shadows.

Than I disabled caves an deco again and installed the v6 caves mod. Even with my modifications I had immediately shadows.

It seams that I can't make a heightmap check because of the overgeneration of the caves. There is no heightmap outside the actual mapchunk.

But I will find a way

**Comment by duane-r** [comment]
Valleys can't calculate terrain height unless it happens to fall inside the current chunk. It's supposed to just set the heightmap to higher or lower than the borders of the chunk in that case, so you know it's a useless value. However, it's not working for some reason. (https://github.com/minetest/minetest/issues/4150) If the heightmap shows a vast number of any of the same height, you can bet it's well above or well below ground, so I put a sanity check in fun_caves/master, which I'll push shortly.

On topic, I'll see if I can get a screenshot of the shadows I was seeing. I'm pretty sure I didn't have any extra mods active, but I might be mistaken. It was the same lines of square shadows though.

**Comment by MarkuBu** [comment]
The shadows are not always square. I posted a new thread in the forum with a screenshot and some informations.

And this bug happens with other mods too. A known mod is moretrees. But you are right, I saw these shadows also in vanilla minetest. But very rare. With the v6 cavegen I saw 3 or 4 shadows around the spawn point with a view range of 150

**Comment by MarkuBu** [comment]
The mod works fine with v6 mapgen. I think, the problem is related to the same issue like moretrees. I will focus on another project until this bug is fixed

**Comment by duane-r** [comment]
I can't get anything to show shadows now. I wonder if it has to do with recompiling minetest twice yesterday.

**Comment by MarkuBu** [comment]
Shadow bug fixed

https://forum.minetest.net/viewtopic.php?f=6&t=14718&p=218433#p218433

Now I try to fix the destroyed trees and the flying plants. Would be no problem if lua mapgens could run before decoration

**Comment by MarkuBu** [comment]
I have already found a solution to fix the floating/destroyed plants bug and made some code cleanup.

If I finished testing, will you update your repo or should I open my own?

**Comment by duane-r** [comment]
Why don't you publish your fork, since you're actively maintaining it? I'm focused on my noise-based caves.

As for the decoration issue, there is a solution, but you probably won't like it -- clear all the decorations in the init.lua and place them with your lua code. (Nuke the site from orbit.)

**Comment by MarkuBu** [comment]
> As for the decoration issue, there is a solution, but you probably won't like it -- clear all the decorations in the init.lua and place them with your lua code. (Nuke the site from orbit.)

Tried, but failed. See my last post

https://github.com/minetest/minetest/issues/4144

**Comment by duane-r** [comment]
You misunderstand. I mean store all the decoration tables, then use minetest.clear_registered_decorations(), then make your own loop to place the decorations from the table data.

**Comment by MarkuBu** [comment]
I guess this would cause a pretty nice lag. 

I'm not totally happy with the current solution, but it works not so bad at all. I will tinker a little bit and try to optimize speed, then I upload the code to github

I think we can close this issue

**Comment by MarkuBu** [comment]
> I mean store all the decoration tables
Can you tell me how to store the decoration?

**Comment by duane-r** [comment]
Check the valleys_c/deco.lua file. It's just a matter of copying them into a table. Of course, you then have to figure out how to place them manually, which would be difficult.

**Comment by duane-r** [comment]
I'm removing the v6 branch. Let me know if you spot this in the master.
