### ISSUE TITLE
More varied food from slime drops and moon juice?

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#10]
It would be interesting to have more choice of edibles in the way of moon juice, and slime drops.  They could even poison (a la red mushrooms from flower mod).  The moon juice could return an empty drinking glass from the vessels mod.

**Comment by everamzah** [comment]
I'm using https://github.com/everamzah/fun_caves/commit/0cf63f17308441f86b1a93a167c45079182e364e for now.  Not sure about it though.

**Comment by duane-r** [comment]
I'd just hate to use moon juice for food. I'd rather save it for moon glass.

**Comment by everamzah** [comment]
Yeah, I never use it.  I'll likely make a separate bandaging mod using glue from slime drops with cotton and paper.
