### ISSUE TITLE
Wild mushrooms on the surface

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#14]
They seems to grow fast enough, and take over a large swath of surface area quickly.

![screenshot_20160601_061102](https://cloud.githubusercontent.com/assets/1761623/15706213/713a2f28-27c0-11e6-80d2-39648068cef0.png)

This world is a few days old now.

**Comment by MarkuBu** [comment]
Now you have enough food forever ;-)

**Comment by everamzah** [comment]
I'm experimenting locally with modified (increased) ABM interval times for *mushroom spread* and *new mushrooms* independent of `fun_caves.time_factor` (L#217 and L#242).  One alternative may be to check for `dirt_with_dry_grass` and `dirt_with_grass`, which only grow with light themselves, and rarely underground.

**Comment by duane-r** [comment]
I don't like giant mushrooms on the surface. Besides, it's easy to grow food up there.

**Comment by everamzah** [comment]
Yes, and they spread pretty wildly out of control up there.  Also, having a wide open scene full of mushroom caps and stems (nodeboxes) seems to really slow rendering speed.

What about red/brown mushrooms converting to huge only if they're *not* on dirt_with_grass or dirt_with_dry_grass?

**Comment by duane-r** [comment]
Ok, I misunderstood your intention here. I've set an altitude limit on the huge growth.

**Comment by everamzah** [comment]
1da72bfa400abb0b51d1c5f986fd38d3ca326675
