### ISSUE TITLE
Transcoder pairs not persisting between restarts

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#30]
I had an unrelated server crash, and when I restarted the transcoders I had placed prior to the crash no longer worked.

I'm not sure what can be done about that.  If they're saving data on shutdown only, perhaps an periodic autosave could be used.

**Comment by everamzah** [comment]
Okay, once I tried to dig one of the non-working ones, I got a crash again:
```
2016-06-28 11:42:21: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback node_on_dig(): /home/james/.minetest/mods/fun_caves/tesseract.lua:396: attempt to get length of local 'pair' (a nil value)
2016-06-28 11:42:21: ERROR[Main]: stack traceback:
2016-06-28 11:42:21: ERROR[Main]:       /home/james/.minetest/mods/fun_caves/tesseract.lua:396: in function </home/james/.minetest/mods/fun_caves/tesseract.lua:380>
```

**Comment by everamzah** [comment]
I just crafted a pair, placed them and they worked fine.  I didn't see anything in fun_caves_data.txt so I /shutdown.  Then the file had a string in it, and I restarted the server.  I looked at the file again and it was empty.  The transcoders that had worked prior to /shutdown no longer functioned.

**Comment by duane-r** [comment]
Data saves here, no more often than every dps_delay seconds: https://github.com/duane-r/fun_caves/blob/master/abms.lua#L73

After the last two commits, I can't get it to crash by removing the text file. I'm not sure why it wouldn't be saved unless your server is caching writes for a long time.

**Comment by duane-r** [comment]
I've added an attempt to save the database at shutdown, but the problem seems to be that the engine isn't saving node metadata if you shutdown quickly. I don't know if there's any way to correct that.

**Comment by everamzah** [comment]
I'm saving every 15.3 seconds, so maybe that's why.  Of course I'll continue to test and experiment.  It seemed that if I tried to dig a transcoder after a restart, if the data didn't save right, that's when it would crash.

**Comment by duane-r** [comment]
I added ownership to them, and thought I'd set it up to tag them with whoever digs them up if they aren't owned, but I still lost my first pair. Hopefully, any future sets won't have that problem.

**Comment by everamzah** [comment]
Transcoders seem to be persisting correctly.  Thanks!
