### ISSUE TITLE
Hunger bar at different DPIs

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#38]
133
--
![screenshot_20160703_163158](https://cloud.githubusercontent.com/assets/1761623/16547434/b6be1e30-413b-11e6-9093-7e571ac4418d.png)

96
--
![screenshot_20160703_163039](https://cloud.githubusercontent.com/assets/1761623/16547435/bae982d8-413b-11e6-82a3-2cdb5529f455.png)

72
--
![screenshot_20160703_163015](https://cloud.githubusercontent.com/assets/1761623/16547436/c01ebce6-413b-11e6-913b-abc40768e415.png)

**Comment by duane-r** [comment]
Try it now and see if it works. It seems to work when I resize the window after starting anyway.

**Comment by everamzah** [comment]
Perfect now!
