### ISSUE TITLE
Molten gold not defined for bucket

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#4]
The molten gold liquid isn't registered with bucket.register_liquid().  It's easy to remove molten gold sources by placing something over them, but with a bucket you get a little reward.

**Comment by duane-r** [comment]
I've never made up my mind about what "molten gold" should drop. I was always worried that somebody would use the gold goblins as a gold generator, though I'm not sure why that would be a big deal. I considered making it some kind of "fool's gold" that wasn't useful. What do you think?

**Comment by everamzah** [comment]
For me, I just want to be able to scoop the molten gold liquid source, and place it elsewhere for decorative purposes.  Basically, because it's a liquid, I feel it should be registered with the bucket mod.

If you agree, and would like I can try for a PR.

**Comment by everamzah** [comment]
It wouldn't need to have a recipe to gold, but that would be interesting.  Like lava buckets, I'd assume it would have a long fuel time for use in furnaces.

**Comment by everamzah** [comment]
#18

**Comment by duane-r** [comment]
https://github.com/duane-r/fun_caves/commit/57ab4c49fd38ce03148701635b3675b7ea45f018
