### ISSUE TITLE
Unknown item on crafting of syrup

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#42]
Placing an empty bottle and a bucket of sap on the craft grid, results in an unknown item:  fun_caves:bucket_empty

I haven't found yet where it's occurring, maybe treegen.lua craft prediction replacements.

**Comment by duane-r** [comment]
https://github.com/duane-r/fun_caves/commit/de4d2b7b521208e133568a65e3cc8add2aa0db6c

There may be other glitches with all the extra checks I put in. Hopefully fewer crashes though.
