### ISSUE TITLE
Meteor sky is persistently white

### ISSUE THREAD

**Issue by taikedz** [duane-r/fun_caves#46]
**Issue**

When a meteor strikes, the sky is turned white. On my server (using commit 812dcca ?) the sky was not being reverted thereafter.

**Expected**

Sky should revert to normal after 1 second

**Reproduce**

* connect to play.ducakedhare.co.uk:30000
* wait for a meteor strike (if you manage not to get killed!)

**Comment by taikedz** [comment]
I did an update which broke things, then reverted.... and the issue has gone away....... hmm....

**Comment by duane-r** [comment]
This might help.

https://github.com/duane-r/fun_caves/commit/ae0886a397f7c170280ac2a52bd2dee51f1c30e1
