### ISSUE TITLE
Falling entities glitch on/near some mushroom caps.

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#6]
When a number of falling entities drop onto the mushroom caps, they'll sometimes get caught up and glitch in their movement.  This usually occurs when there's a falling entity above and beside the cap.

**Comment by duane-r** [comment]
That's due to the giant caps extending beyond their cube. The only solution I can think of for that would be to just use the huge caps for everything, and I'm not sure I'm willing to do that.

**Comment by duane-r** [comment]
I could do this.

![tall mushrooms](https://forum.minetest.net/download/file.php?mode=view&id=6379&sid=eaccc5759fde753db8041a014d49eb9d)

**Comment by everamzah** [comment]
I like it.  The shape seems fine, and it's just a matter of getting used to a new color.  That new color I think is better than the original.

**Comment by everamzah** [comment]
@duane-r there was an issue with falling entities in the doors mod of minetest_game.  I believe they used an airlike drawtype to remedy the issue?  Or is there not a way to define the cap such that entities are allowed to pass?

**Comment by duane-r** [comment]
They just made it walkable. That might be a good idea. The nodes don't fill a cube, so objects that fall on them look weird anyway. If they're walkable, that would just cover them up. However, I need to check if walkable nodes can be picked. (I don't think so.)

The texture I'm using is from the HDX, hi-res textures, not appropriate for the main mob.

**Comment by duane-r** [comment]
https://github.com/duane-r/fun_caves/commit/35e6699a5683e3c680945ef66fc3c248f2c40bff
