### ISSUE TITLE
Solid color for radioactive ore?

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#7]
Salt with radioactive ore is all green.

![screenshot_20160529_130805](https://cloud.githubusercontent.com/assets/1761623/15634956/22ac64de-259f-11e6-8634-3bdfd2c991ca.png)

![screenshot_20160529_130811](https://cloud.githubusercontent.com/assets/1761623/15634955/22ac2cc6-259f-11e6-82f0-6841e5d874ca.png)

**Comment by duane-r** [comment]
It uses the caverealms salt texture, which is basically transparent.

**Comment by everamzah** [comment]
Thoughts on this one?
![caverealms_radioactive_ore](https://cloud.githubusercontent.com/assets/1761623/15914167/a3399abc-2dac-11e6-87ce-9724ad940eae.png)

![screenshot_20160608_190850](https://cloud.githubusercontent.com/assets/1761623/15914154/82dc19c0-2dac-11e6-8acd-8f3c6d33980b.png)

**Comment by everamzah** [comment]
e144b2b30080a5907c614f884f052e2c2a516b8d
