### ISSUE TITLE
Sand biomes are falling en masse

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#8]
I was wondering if layering the bottom of sand biomes with sandstone might be appropriate.  Whenever I punch a sand node and they all fall, it causes the server to run at 100% until it can finish updating nodes.  Plus, all the entities cause deserialization errors on the client which also runs at max.

I admit the biomes are fun and the result of them all falling is very nice.  It's just so much overhead!  Thoughts?

**Comment by duane-r** [comment]
Yeah, I can see that being a problem, though I love getting buried in sand now and then. Maybe I can find some middle ground, like put in a partition every so often.

**Comment by everamzah** [comment]
Black sand doesn't fall.  Perhaps the occasional partition using that as a base would be interesting.  I really would hate losing the falling sand in total; it really adds a lot of dynamism to the caves.

![screenshot_20160531_074312_1](https://cloud.githubusercontent.com/assets/1761623/15673320/f7a611f2-2703-11e6-8070-d6eb60e851c9.png)

This area was lit up as if the sky were directly above it.

![screenshot_20160531_074133](https://cloud.githubusercontent.com/assets/1761623/15673345/1e48a0ae-2704-11e6-8ce7-dae5950e8a69.png)

Note the deserialization error in the client.  This area was visited before, but I died here and didn't visit again until now.  I guess a goblin was attacking me while I was waiting for the client/server to finish dropping the sand.  :D

**Comment by everamzah** [comment]
![screenshot_20160530_130232](https://cloud.githubusercontent.com/assets/1761623/15673411/7d78fb78-2704-11e6-96fe-f068027af9fa.png)

**Comment by duane-r** [comment]
Partitions aren't cutting it. I had to do it more thoroughly. You can still trigger the occasional collapse, but it shouldn't black out the server.

https://github.com/duane-r/fun_caves/commit/0edc007f4751e981193dad3dd6a07c103cf0a632
