### ISSUE TITLE
Dry grass (Savannah) biomes lack mobs

### ISSUE THREAD

**Issue by everamzah** [duane-r/fun_caves#9]
I'm using mobs_redo, mobs_monster, mobs_creeper, and mobs_slimes.  It seems that there are no hostile mobs in Savannah.  Perhaps this is something that should be addressed in mobs_monster repo.

**Comment by duane-r** [comment]
Try this one. I don't know if the elephants are hostile, but they should be:

https://forum.minetest.net/viewtopic.php?f=9&t=14382&hilit=elephant

**Comment by everamzah** [comment]
![screenshot_20160531_134238](https://cloud.githubusercontent.com/assets/1761623/15684577/a954b396-2735-11e6-9c3e-18b423f4f979.png)

Ok, working on this now.  Will have to modify because it's dogfight, you have to hit it first.  Additionally, its damage hit range is too low, so it has to be very close (you have to be inside its model, actually) and it will only damage a very small amount.

**Comment by everamzah** [comment]
This is interesting, haven't really tested it yet.  However, what I had in mind was a sort of mob that would chase you into your home.  Maybe it could be a mad, hostile elephant that had an increased walking/running speed?  #12

**Comment by everamzah** [comment]
#15

**Comment by everamzah** [comment]
Now with elephants, tarantulas, and dirt monsters.
